services:
  postgres-database:
    image: postgres:18
    container_name: system_products
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: